server:
  port: 8765

spring:
  application:
    name: spring-cloud-api-gateway

  config:
    import: optional:configserver:http://localhost:8888
    
# Sleuth Sampling percentage config
# 1.0 means 100%
  sleuth:
    sampler:
      probability: 1.0

# Uncomment when not using Custom Routes   
#  cloud:
#    gateway:
#      discovery:
#        locator:
#          enabled: true
#          lowerCaseServiceId: true
    
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
      
  instance:
    preferIpAddress: true