server:
  port: 8000

spring:
  application:
    name: currency-exchange-service
    
# Locale properties file config
  messages:
    basename: message
  
  config:
    import: optional:configserver:http://localhost:8888
    
# Sleuth Sampling percentage config
# 1.0 means 100%
  sleuth:
    sampler:
      probability: 1.0

#DataSource Configuration
  datasource:
    url: jdbc:postgresql://localhost:5432/hibernate
    username: postgres
    password: toor
    driver-class-name: org.postgresql.Driver

  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: update

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
      
  instance:
    preferIpAddress: true
    
resilience4j:
  retry:
    instances:
      sample-api:
        maxAttempts: 5
        waitDuration: 2s
#        enableExponentialBackoff: true

  circuitbreaker:
    instances:
        default:
            registerHealthIndicator: true
            slidingWindowSize: 10
            permittedNumberOfCallsInHalfOpenState: 3
            slidingWindowType: TIME_BASED
            minimumNumberOfCalls: 20
            waitDurationInOpenState: 50s
            failureRateThreshold: 50
            eventConsumerBufferSize: 10
